### ISSUE TITLE
Polish: translation submitted (original)

### ISSUE THREAD

**Issue by Hangur** [nutritionfactsorg/daily-dozen-localization#4]
Both the TSV spreadsheet and README with added Polish are attached.

[Polish_pl.tsv.txt](https://github.com/nutritionfactsorg/daily-dozen-localization/files/5720144/Polish_pl.tsv.txt)

[README.md.txt](https://github.com/nutritionfactsorg/daily-dozen-localization/files/5720143/README.md.txt)

**Comment by marc-medley** [comment]
@Hangur Thanks for the translation. I will add comments/questions/results here that might occur from importing `Polish_pl.tsv` file into the application source code.

There is also related `Polish_pl_appstore.tsv` for product description on the App Store page and in the app info page to be done. Would you or some one else be translating this part? See [daily-dozen-localization/.../Polish/tsv/Polish_pl_appstore.tsv](https://github.com/nutritionfactsorg/daily-dozen-localization/blob/master/Languages/Polish/tsv/Polish_pl_appstore.tsv)

**Comment by Hangur** [comment]
Thanks. I will do the related `Polish_pl_appstore.tsv` as well.

**Comment by marc-medley** [comment]
@Hangur some comments and questions below...

**Source Source**

> I am not sure, if I should translate this term to Polish. The Polish version doesn't sound very natural and can be actually more confusing than original term.

For context, "Open Source" is the `Info` menu item which links to the NutritionFacts Open Source web page.

* [NutritionFacts: Open Source](https://nutritionfacts.org/open-source/)
* [Wikipedia: Otwarte oprogramowanie](https://pl.wikipedia.org/wiki/Otwarte_oprogramowanie)

_Just to confirm, for the menu item title, what would you find to be most meaningful and least confusing "Open Source" or "Otwarte oprogramowanie" or something else?_

![Info_OpenSource](https://user-images.githubusercontent.com/15098151/102936942-f6e85280-445d-11eb-82e9-8ea765a3af2c.png)

_Imperial & Metric Weight_

As an international application, the Daily Dozen software currently has a user preference setting to choose imperial or metric measurements for all languages.

Perhaps a future software version can hide the units type choice for all-metric locales. 

Let's consider the current case where the user can select either imperial or metric units. _If a Poland user did choose the weight units setting of "Imperial", what would be preferred to show? "Waga (lbs)" or "Waga (pounds)" or "Waga (funt)" or "Waga (funtów)" or something else?_

**Missing Translations**

The following times did not have Polish translations in the tsv file:

* "Measurement Units"
* "Enable Reminders"
* "Daily Reminder Settings"
* "Advanced Utilities" -- will show items like import and export database.

![Settings](https://user-images.githubusercontent.com/15098151/102936536-319dbb00-445d-11eb-9283-c4565137c013.png)

![EnableReminders](https://user-images.githubusercontent.com/15098151/102937803-d0c3b200-445f-11eb-821f-bb5f5b9bf342.png)

**Comment by Hangur** [comment]
> Just to confirm, for the menu item title, what would you find to be most meaningful and least confusing "Open Source" or "Otwarte oprogramowanie" or something else?

I researched a bit more, and it seems that the term `open-source` is generally preferred to be left as it is. It can be translated but the English version is something that, I believe, is more likely to be associated with the whole `open-source` idea. I would go with the original English term.

> Let's consider the current case where the user can select either imperial or metric units. If a Poland user did choose the weight units setting of "Imperial", what would be preferred to show? "Waga (lbs)" or "Waga (pounds)" or "Waga (funt)" or "Waga (funtów)" or something else?

For the "Imperial" settings, that should be shown as "`Waga (funt)`".

> The following times did not have Polish translations in the tsv file:
> 
> "Measurement Units"
> "Enable Reminders"
> "Daily Reminder Settings"
> "Advanced Utilities" -- will show items like import and export database.

I remember these. I was wondering whether to translate them or not. I think I misunderstood the directions `The columns which begin with lang_ are to be translated.` - as columns in the tsv file with these terms were empty. Respectively, they are:

```
Measurement Units - Jednostki miary
Enable Reminders - Włącz przypomnienia
Daily Reminder Settings - Ustawienia codziennych przypomnień
Advanced Utilities - Zaawansowane narzędzia
```

Ckecking the terms now, made me think of one other term `Daily reminder`. I understood it as in "a reminder that prompts the things/habits that are going to appear per this one day", that you can set individually per every day (that's why it is currently translated as `Dzienne przypomnienie`), but I am thinking now, that it meant "a reminder that is triggered every day"? If that is the case I would switch it to `Codzienne przypomnienie` instead.

As for the changes you requested, I can re-upload the file. Alternatively, I am also comfortable with git, so I can edit it once it is committed and make a PR. Let me know.

**Comment by marc-medley** [comment]
@Hangur `Daily reminder` would be "a reminder that is triggered every day".

For changes, I do run some additional checks on the file beyond a standard text file merge process. Programming source code languages have the benefit of compiler checks and warnings after a merge. However, the git diff & merge for a tab-separated text file does not includes such checks and warning... so, additional checks are added as appropriate for managing the intake of NutritionFacts application translations.

It's OK to just re-upload the file.  

Alternately, a PR would also work if the changed file is added with a different file name.  For example, a date can be added `Polish_pl_20201224.tsv`.  Then I can work with `Polish_pl_20201224.tsv` and `Polish_pl.tsv` at the same time with additional tools.

**Comment by Hangur** [comment]
Thanks. I am re-uploading the `Polish_pl.tsv` and uploading `Polish_pl_appstore.tsv`.

I incorporated the previous changes into this new file. I also introduced small changes (in both above-mentioned files)  when it comes to the word `foods` - as in Polish `pokarm` and `żywność` is used interchangeably, depending on what "sounds" better, more natural in a given situation.

Let me know if there is anything more I can help you with.

[Polish_pl.tsv.txt](https://github.com/nutritionfactsorg/daily-dozen-localization/files/5748503/Polish_pl.tsv.txt)
[Polish_pl_appstore.tsv.txt](https://github.com/nutritionfactsorg/daily-dozen-localization/files/5748504/Polish_pl_appstore.tsv.txt)

**Comment by marc-medley** [comment]
@Hangur 

Just to confirm, each item on the following two lists should retain the same spelling as English?

_Physical Activity (Sports)_

* Jogging
* Lacrosse
* Racquetball
* Rugby
* Snorkeling
* Squash
* Surfing
 
_Foods_

* Miso
* Okra
* Oregano
* Popcorn
* Tempeh

> I am not sure about the context here? And I have doubts how would it fit when translated to Polish. 

The Android store and Apple Store `android.store.whatsnew` and Apple Store `apple.store.whatsnew` would be seen on the Android "Nowości" and Apple "Co nowego". So, "Dodaje obsługę języka polskiego." appears to fit OK.

* [Apple App Store: Dr. Greger's Daily Dozen `Poland (PL)` ⇗](https://apps.apple.com/pl/app/dr-gregers-daily-dozen/id1060700802?l=pl)
* [Google Play: Dr. Greger's Daily Dozen `pl` ⇗](https://play.google.com/store/apps/details?id=org.nutritionfacts.dailydozen&hl=pl)

**Comment by Hangur** [comment]
As for the items on the two lists you asked, yes - they are to be kept in English. 

From the list `Physical Activity (Sports)` only `snorkeling` and `jogging` are more or less available in Polish - the rest is used in their original English terms. But, 
- the first one sounds quite uncommon and more puzzling in Polish ("nurkowanie z rurką", which means "diving with a tube") than in English; 
- and the latter (when it is being used e.g. in some fitness articles - usually stays as it is) translates the same as `running`, which is already on the Daily Dozen list. 

From the list `Foods` only `Okra` and `Popcorn` required a bit more consideration. 
 - `Okra` may be `Okra` or `Ketmia jadalna` or `Piżmian` , but the last two sound more like something a botanist or a gardener might know about, not a regular person.
 - `Popcorn` appears in two possible ways - as `Popcorn` and `Prażona kukurydza` (literally, `roasted corn`), and I think that the English way would be much more explanatory and providing less confusion. 

> So, "Dodaje obsługę języka polskiego." appears to fit OK.

I am still not sure about it. The expression `Dodaje obsługę języka polskiego` means that `he/she/it` (it is implied by the form of the verb) adds it. And it is a bit weird and unnatural in this situation. Unless it is meant to say that the app itself adds this? Daily Dozen adds it? Usually, when writing down things like updates, the impersonal form of the verb would be used: `Dodano obsługę języka polskiego` (as in 'Polish translation has been added'). 

If I look at my Android Store, it looks like this:
![greger](https://user-images.githubusercontent.com/44006666/103387025-cbbace80-4b01-11eb-8c26-9dfc04079496.jpeg)

So if the new update is going to show a similar message - I would definitely go for **`Dodano obsługę języka polskiego`** as opposed to **`Dodaje obsługę języka polskiego`**.

**Comment by Hangur** [comment]
@marc-medley hey, I was wondering how is it going with this issue? Is there anything I can help with? Let me know.

**Comment by marc-medley** [comment]
@Hangur thanks for checking in!  There are some items that have been added to the spreadsheet TSV files. These items were not present in the original files.

[Polish_pl.tsv](https://github.com/nutritionfactsorg/daily-dozen-localization/blob/master/Languages/Polish/tsv/Polish_pl.tsv) (3 rows)

* `reminder.alert.text` text that the daily reminder presents to the user.
* `reminder.state.off` daily reminder on/off setting
* `vibrate` daily reminder setting

[Polish_pl_appstore.tsv](https://github.com/nutritionfactsorg/daily-dozen-localization/blob/master/Languages/Polish/tsv/Polish_pl_appstore.tsv) (7 rows)

* Text in app store screenshot graphics. Same text for [Android](https://play.google.com/store/apps/details?id=org.nutritionfacts.dailydozen&hl=en) and [Apple](https://apps.apple.com/us/app/dr-gregers-daily-dozen/id1060700802
). (6 rows)
* Keywords to support app store search (1 row)

I'm finishing the final coverage checks this week to see if anything else is missing. And, I will let you know how these check find any other items to translate or if translation is good to go into app release testing.

**Comment by Hangur** [comment]
@marc-medley thanks for getting back to me!

I made changes in the rows you mentioned above to match the updated spreadsheet TSV files. I am re-uploading them - I hope everything is there this time :)

I also found and fixed one typo (`cozienne` changed to `codzienne` in 1 row) and one of the repeating `21 Adaptacji` was written with a small "a", changed that for keeping the consistency up.

If you need any other changes/additions/help, please let me know.

[Polish_pl.tsv.txt](https://github.com/nutritionfactsorg/daily-dozen-localization/files/5896312/Polish_pl.tsv.txt)
[Polish_pl_appstore.tsv.txt](https://github.com/nutritionfactsorg/daily-dozen-localization/files/5896313/Polish_pl_appstore.tsv.txt)

**Comment by senpl** [comment]
I corrected most important part in android version:
Proposed changes:
1. Most important. English cup is in polish more "filiżanka" than szklanka - glass (small glass 250ml/typical glass 300ml). This is especially important in nonimperial translations when only one string version is provided(so mainly in 21 tweaks texts).
2. Szybki marsz (6 km/h) correct recalculation, previous was not correct.
3. Nurkowanie i nurkowanie głębinowe instead on english versins.
4. pea ang english peas translations inverted as it should be.
5. kapusta pastewna as Collard greens
6. Plout as Śliwa
7. skating and speed skating is more jazda na rolkach , name łyżwiarstwo is discipline not really relevan to this activity.
8. in polish we do not usually use coma before and So sth, sth, and sth. should be more common as "sth, sth i sth" (without comma before and).
9. 21 adnotacji should be replaced with 21 wskazówek as more intentional translation
10. Many other small changes

Of course changes could be discussed. If my changes would be accepted it could be applied to appstore version as well.
I prefer my translatins of 21 Tweaks but it is more work for translators of book , just to make it like in book(So if it could be found should be used).
Words like Randomizwane and implementacyjne are correct in polish language, but got nicer polish equivalents, but this is just my opinion so I not left it as they are.
Anyway good job. Sometimes their are nicer then mine in [my translation](https://github.com/nutritionfactsorg/daily-dozen-android/pull/164/files#diff-92f7518f16e2bf44fd39c49eba3e984bde4b63f35d16aa2d8d76f569f9eb629a).
[Polish_pl1.tsv.txt](https://github.com/nutritionfactsorg/daily-dozen-localization/files/5913787/Polish_pl1.tsv.txt)

**Comment by Hangur** [comment]
@senpl Thanks for the feedback! 

I will check it more thoroughly tomorrow, I just briefly browsed your comments and the first one struck me as not entirely correct. Indeed English `cup` is more like Polish `filiżanka`, but when it comes to measuring ingredients, e.g. in culinary recipes it is `szklanka` that is commonly used, and it is a standard that one should use a `szklanka` that has 250 ml, when used for culinary measurements. 

This is a cup used for culinary measurements. 250 ml capacity. 
![cup 01](https://user-images.githubusercontent.com/44006666/106745453-69ce1700-6621-11eb-85b8-2c58dddb4bf5.jpg)

After writing `cup capacity,` that is the first response in Google. It says in the very top, that, indeed, 'The most common are glasses with a capacity of 150-330 ml.' **BUT**

> The recipes usually assume that the glasses have a standard capacity, i.e. 250 ml.

![cup 02](https://user-images.githubusercontent.com/44006666/106745458-6aff4400-6621-11eb-9354-f8fc337dd850.jpg)


When cooking, one rarely uses `filiżanka` measurements - I am a frequent user of cookbooks and culinary blogs (both Polish and English ones), and I would never use `filiżanka` when trying to re-create the English recipe in Polish reality :) Google itself finds only 933.000 results for `filiżanka mąki` vs 3.990.000 results for `szklanka mąki` (cup of flour). That's why, when submitting this translation, I made a conscious choice between `filiżanka` and `szklanka`.

![filiżanka](https://user-images.githubusercontent.com/44006666/106659851-90e40480-659f-11eb-8589-9c007cd7fa43.png)
![szklanka](https://user-images.githubusercontent.com/44006666/106659852-917c9b00-659f-11eb-8f0d-49f3e5deb8ed.png)

As for the other points, I will check if your proposals are in line with the research I've already made.

**Comment by senpl** [comment]
OK. So translation from cup to szklanka seems ok, and not require change. From my experience it is just nicer when it writes 1 szklanka (250 ml) , but ok. It will not change much in most cases, just more of good things. So all my changes of szklanka could be ignored.

**Comment by Hangur** [comment]
As for the other points, that you made @senpl 

**2.** 

>Szybki marsz (6 km/h) correct recalculation, previous was not correct.

**Thanks for spotting!** `4 mph` is indeed probably `miles per hour` - I unconsciously took it as `meters per hour`.


**3.** 

> Nurkowanie i nurkowanie głębinowe instead on english versins.

If we are adamant on using Polish translation here, then the proper name for `snorkeling` is `nurkowanie z rurką`. Both terms are used interchangeably on Polish websites/in articles about diving and also snorkeling, written as it is, is used on Polish [Wikipedia](https://pl.wikipedia.org/wiki/Nurkowanie) as a type of diving.

As for Polish term `nurkowanie głębinowe` (deep diving) - it is not exactly the English `scuba diving` as it is too specific. 

`nurkowanie głębinowe` is described on Wikipedia as 

> (...) underwater diving to a depth beyond the norm accepted by the associated community. In some cases this is a prescribed limit established by an authority, and in others it is associated with a level of certification or training, and it may vary depending on whether the diving is recreational, technical or commercial.

**while** `scuba diving` is just a broad term (that includes deep diving) for 

> underwater diving where the diver uses a self-contained underwater breathing apparatus (scuba), which is completely independent of surface supply, to breathe underwater." 

If we were to translate it to Polish, then `nurkowanie z akwalungiem` would be more proper.


**I am more for leaving the English terms here**, but if translating to Polish, it is better to stick with the proper names `nurkowanie z rurką` (snorkeling) and `nurkowanie z akwalungiem` (scuba diving).


**4.** 

> pea ang english peas translations inverted as it should be.

**I guess that makes more sense.** The dry version usually is called `groch`, while the fresh one - `groszek`. Even though both are having an official name of `Groch zwyczajny` :) 

**5.** 

> kapusta pastewna as Collard greens

I don't think we should put it like that. The proposed `kapusta pastewna` is basically a common, green cabbage, which is not what collard greens are. 

(Wikipedia)
> Collard refers to certain loose-leafed cultivars of Brassica oleracea, the same species as many common vegetables, including cabbage (Capitata Group) and broccoli (Italica Group). (...) The name "collard" comes from the word "colewort" (a medieval term for non-heading brassica crops).

Collard greens (Brassica oleracea Viridis group) are type of Acephala ("non-heading") group that remains most like the natural wild cabbage in appearance. They are cruciferous, they are from 'cabbage family', but **they are not 'kapusta pastewna'**. 

**I think it should be left as** `collard greens`, as it seems there is not a proper, official Polish name for them. 

**6.** 

> Plout as Śliwa

I believe that this is not correct. 

(Wikipedia)
> Pluots, apriums, apriplums, or plumcots, are some of the hybrids between different Prunus species that are also called interspecific plums. Whereas plumcots and apriplums are first-generation hybrids between a plum parent (P. salicina or P. cerasifera or their hybrids) and an apricot (P. armeniaca), pluots and apriums are later-generations. Both names "plumcot" and "apriplum" have been used for trees derived from a plum seed parent, and are therefore equivalent.

`Śliwa` is a plum. 

The word `Śliwomorela` is exactly the term for `plout`.

You can buy those in the gardening [stores](https://www.sadowniczy.pl/product-pol-138934-Sliwko-morela-Sliwomorela-Plumcot-START-PACK-R.html), there are gardening articles written [specifically](https://wojtekwogrodzie.wordpress.com/sliwomorela/#:~:text=Poniewa%C5%BC%20w%20nazewnictwie%20%C5%82aci%C5%84skim%20%C5%9Bliwa,moreli%2C%20od%20kt%C3%B3rych%20si%C4%99%20wywodzi.) about them. 

**In short**, `Plout` is a separate type of fruit and the name for it exists already in Polish language - `Śliwomorela`.

**7.**

> skating and speed skating is more jazda na rolkach , name łyżwiarstwo is discipline not really relevan to this activity.

Based what I read on Wikipedia:
> Speed skating is a competitive form of ice skating in which the competitors race each other in travelling a certain distance on skates. 

and in Cambridge Dictionary:
> the sport of racing on ice, usually around an oval track

That's why I think `Łyżwiarstwo szybkie` is a more appropriate naming here.

**8.**

> in polish we do not usually use coma before and So sth, sth, and sth. should be more common as "sth, sth i sth" (without comma before and).

That is not exactly correct. Please check below:
- https://polszczyzna.pl/przecinek-przed-i-kiedy-postawic/
- http://www.jezykowedylematy.pl/2010/12/emil-rucinski-kiedy-przed-i-trzeba-postawic-przecinek/
- https://www.ekorekta24.pl/przed-ril-nie-stawia-sie-przecinka-czyli-mity-polskiej-interpunkcji/

Example from: https://www.prosteprzecinki.pl/przecinek-przed-i  :

![przecinki](https://user-images.githubusercontent.com/44006666/106767192-e6212400-663a-11eb-871b-479a7f30a7e7.png)

It says above that:

> When the word `i` is repeated, we put a comma in front of the second (and each subsequent) `i`.

We will go there on Monday, and Tuesday.

She was beautiful, and smart, and good.

**9.**

> 21 adnotacji should be replaced with 21 wskazówek as more intentional translation

My `21 adaptacji` (not 'adnotacji') was just a proposal, as it is the closest to "tweaks". I have thought of `wskazówki` myself, but they mean `tips` and they convey less of the meaning behind the word 'tweak' ('improve (a mechanism or system) by making fine adjustments to it.'; from Oxford Languages) while 'adaptacje' ('adaptations') has the connotation of an adjustment ('the action or process of adapting or being adapted'; from Oxford Languages).

**I'd leave the decision up to the person in charge of the app updates.** And it definitely **should be adjusted later**, when the official Polish translation of `21 Tweaks` comes out in another of Dr Greger's books, to agree with the app's terminology.

**10.**

> Many other small changes

I will look into those a bit later and respond in a separate comment, if needed.

**Comment by Hangur** [comment]
@marc-medley I was wondering about one thing...

In Polish official translation of dr Greger's book ('How not to die'), `Daily Dozen` is referred to as `Codzienny Tuzin`. My concern is whether in Polish translation of the app, it shouldn't be the same name. I originally left it as `Daily Dozen dr Gregera`, treating it as a proprietary name, same as the names in case of Whatsapp or Facebook which are not translated into Polish.

Let me know please, what is your opinion on this.

**Comment by marc-medley** [comment]
@Hangur I now have an automated process which reports coverage based on both the Android & Apple source files.  The process found the items listed in `Polish_pl_Additions.tsv` which have not been in the previous spreedsheets for your translation efforts.

Please see: [Polish_pl_Additions.tsv](https://github.com/nutritionfactsorg/daily-dozen-localization/blob/master/Languages/Polish/tsv/Polish_pl_Additions.tsv)

`Polish_pl_Additions.tsv` is pre-populated with translations (provided by @senpl) for your consideration.  Perhaps having these initial translations in-place for consideration can save some time for you.

We can update the choice of `adaptacji` for tweaks should an official Polish translation of the _"How Not to Diet"_ book become available.

Currently, `Daily Dozen` is not translated for the app icon on the launch screen. On Apple iOS, the application is multi-lingual. So, a person in any country can select any supported language, without having to change the default phone language choice. 

`Codzienny Tuzin` would be appropriate for _inside the application_.  A partial screen capture from the Spanish app display is attached as an example: 

![DailyDozen](https://user-images.githubusercontent.com/15098151/106863784-daa31c80-667d-11eb-81cc-5649dab24244.png)

**Comment by Hangur** [comment]
@marc-medley thanks! Will take a look.

**Comment by Hangur** [comment]
Hey @senpl I checked the rest of the changes you made to the file and I am okay with most/many of them them staying - I adapted my own file (attached below) to reflect those changes. 

[Polish_pl.tsv.txt](https://github.com/nutritionfactsorg/daily-dozen-localization/files/5935916/Polish_pl.tsv.txt)


I find the changes that you applied in some of the sentences beneficial to the initial translation. With that in mind, I have some comments to some of the proposed modifications.


## Terms

1. As for the terms discussed in the points 1-10 above:

I haven't changed things proposed in points: 1, 5, 6, 7, 8 (couldn't find the mentioned place with commas), 9 (I guess this is still to be decided, so I left it for now as '21 Adaptacji`).

I applied the things proposed in points: 2 (fixed the '4' to '6'), 3 (changed names to official Polish names), 4 (swapped the names a bit, but added 'zwyczajny' to 'groszek'. I [read](https://www.kuchniaplus.pl/artykuly/groch-i-groszek) a bit about 'groch' and 'groszek' and that made the most sense.)


2. The changes in the naming of the sports

- ***fencing*** - `szermierstwo` to `szermierka`
- ***ice-skating*** -  `łyżwiarstwo` to `jazda na łyżwach`
- ***waterskiing*** - `narciarstwo wodne` to `narty wodne`
- ***water jogging*** - `Jogging w wodzie` to `Jogging wodny`

even though they are more of a cosmetic change and rather subjective, in overall it sounds less imposing and official, so I guess it is a better choice indeed :+1:  (***I updated my file with these***)


3. ***Bicycling uphill*** - from my `Jazda rowerem pod górę` to `Kolarstwo górskie` (here actually, I wrongly assumed it was just a riding one's bike uphill...) - so thanks for correcting me! (***Also updated!***)


4. As for the `Rock climbing` translated by you as `wspinaczka` (***climbing***) - I guess it makes sense to leave it as a [broader term](https://8a.pl/8academy/rodzaje-wspinaczki-wspinaczka-gorska/) and not to narrow it to only one type of climbing. (***Updated!***)


5. ***Play sound*** - it is true that it would in normal circumstances be more of a `odtwarzaj dźwięk` than `włącz dźwięk`. But, firstly, if you go to app's Daily Reminder Settings it is just a toggle button that turns on the sound of a reminder, so we are not really going to play any sounds (like the 'odtwarzaj dźwięk' implies), but we are going to enable the sound for the alarm. Secondly, here also Google results show a preference in using the term `włącz dźwięk`.

![odtwarzaj](https://user-images.githubusercontent.com/44006666/107099754-d2301a80-6812-11eb-9598-bf15f0238239.png)
![włącz](https://user-images.githubusercontent.com/44006666/107099756-d3614780-6812-11eb-9767-607accd64a6a.png)



## Sentences

:pushpin: In a few places (points 1-4) I had a problem understanding why your translation does not reflect the English text. That's why I left those places with my initial translation. 

1. In your translation of

> Time your metabolism-boosting two cups of cool or cold unflavored water before each meal to also take advantage of its preload benefits.

you mentioned only one cup of water - ***I changed it*** to two, to match the English version.


2. In the sentence starting with

> As the first course, start each meal  (...)

you added `(poniżej 100 kcal/140g)` - I am not sure where did you take these numbers from?


3. In the sentece starting with

> Drink three cups a day (...)

you translated `but never exceed three cups of fluid an hour` to `ale nigdy nie przekraczaj jednej szklanki płynu na godzinę`. You mention only one cup instead of 3 cups - what is the reasoning here?


4. In the sentence starting with

> Check this box if your urine never appears darker than a pale yellow (...)

I have the same question as in point 5. You are changing the numbers of the water mentioned in English version and I am not sure on what basis.

___

:pushpin: Here (points 5-7), I ***disagreed*** with introduced changes and didn't include them in the attached above file:

5. The `randomized, double-blind, placebo-controlled clinical trials` that appear in a few places should be translated as `randomizowane, podwójnie ślepe, kontrolowane placebo badania kliniczne`. ***There is no*** `kontrolowane na placebo`. 

Example from [The portal for rare diseases and orphan drugs](https://www.orpha.net/consor/cgi-bin/ResearchTrials_ClinicalTrials.php?lng=PL&data_id=92811&ClinicalTrialName=GALACCTIC--Randomizowane--podwe-nie--ulepe--kontrolowane-placebo-badanie-III-fazy-OSI-906-u-pacjente-w-z-miejscowo-zaawansowanym-lub-przerzutowym-nowotworem-kory-nadnerczy&title=GALACCTIC:%20Randomizowane,%20podw%C3%B3nie%20%C5%9Blepe,%20kontrolowane%20placebo%20badanie%20III%20fazy%20OSI-906%20u%20pacjent%C3%B3w%20z%20miejscowo%20zaawansowanym%20lub%20przerzutowym%20nowotworem%20kory%20nadnerczy&search=ResearchTrials_ClinicalTrials_Simple)

6.  In the sentence starting with

> Randomized controlled trials (...)

***I think it is best*** to leave it as `Randomizowane badania z grupą kontrolną` and not merely as `Randomizowane badania` - I believe it is a valid medical [term](https://toolbox.eupati.eu/glossary/badanie-randomizowane-z-grupa-kontrolna/?lang=pl).

7. In the sentence starting with

> Every two months, create (...)

I slightly modified your change to reflect the English version. Instead of `by wykonać je w określonym czasie lub kontekście` I shortened it to `by wykonać je w określonym kontekście` - as the English version does not mention that there is ***time or context***, just context.

___

:pushpin: As for points 8-10 below I believe it is to be discussed further :question:


8. In the sentence starting with

> Regular self-weighing is considered crucial (...)

you used the term ***stracona waga***, but that is a bit weird, I am not sure if that's correct. There is such thing as ***utrata wagi*** or ***spadek wagi***, and if you Google search it, each of them gives you more results than ***stracona waga***. 


9. In the sentences starting with

> Overweight women randomized  (...)

and 

> Randomized, double-blind, placebo-controlled studies have found that as little as a daily quarter teaspoon of garlic (...)

I am okay with changes of currency from a dollar to Polish zloty, but should we do that? Or it is better to leave it in dollars @marc?


10. In the sentence starting with

> As noted in the Appetite Suppression (...)

I think it feels more natural to say `a systematic review (...) found` as 
`systematyczny przegląd (...) wykazał`
than 
`systematyczny przegląd (...) odkrył`. 

'Wykazał' (showed) vs 'odkrył' (discovered)? 


## Additions

I will have a look at the `Polish_pl_Additions.tsv` that @marc mentioned above hopefully this weekend.

**Comment by marc-medley** [comment]
@Hangur

> There is also evidence to support the use of the spice saffron, _but a pinch a day would cost a dollar, whereas a teaspoon of cumin costs less than ten cents._

A US teaspoon is approximately equivalent to 16 pinches. So, in the US, saffron would be more than (16 x 10) = 160 times more expensive than cumin.  [ Cost Ratio > 160/1 ]

In simplified terms,  the statement would be something like:

> There is also evidence to support the use of the spice saffron, _however, cumin is much more afforable._

In quantified terms, units like `zloty` instead of `dollar` and `cent` probably have more meaning to a Polish speaking person, if the resulting cost ratio is representative of the region.

Which below would you consider most meaningful and useful to the Polish audience? Trust your choice.

* Use `dollar` and `cent`.
* Use `zloty` in a way that approximates the regional cost ratio
* Use simplified terms without either `dollar` or `zloty`

--marc @marc-medley

**Comment by Hangur** [comment]
# TLDR;

@marc-medley , @senpl I managed to take a look at the `Polish_pl_Additions.tsv` file and I introduced some changes - some bigger, some smaller. I explained them below. If there are any `questions / comments / proposals`, let me know.

[Polish_pl_Additions.tsv.txt](https://github.com/nutritionfactsorg/daily-dozen-localization/files/5946047/Polish_pl_Additions.tsv.txt)


@marc, I will compare the zloty/dollar/none options and update the file(s). Also, while checking the `Polish_pl_Additions.tsv` file I did a small correction of `Polish_pl_appstore.tsv`, I am re-uploading it again:

[Polish_pl_appstore.tsv.txt](https://github.com/nutritionfactsorg/daily-dozen-localization/files/5946049/Polish_pl_appstore.tsv.txt)


&nbsp;

## 1. Translating `Tweak`  as `Adaptacja`

Same reason, as I've written [above](https://github.com/nutritionfactsorg/daily-dozen-localization/issues/4#issuecomment-772597933):

> My 21 adaptacji (not 'adnotacji') was just a proposal, as it is the closest to "tweaks". ...


## 2. `Backup` changes

Generally, leaving it as `backup` would work too, but the word `kopia zapasowa` is used commonly in the Polish language. Also, because in other places/file I have translated **backup** it as **kopia zapasowa**, I believe it is better for the consistency to change it remaining places accordingly. Which I did. 

> Backup - **Kopia zapasowa**
Backup failed - **Kopia zapasowa nie utworzona**
Restore Backup - **Przywróć kopię zapasową**
Backup successful	- **Kopia zapasowa utworzona**


## 3. Previous version from appstore file

I've translated this part before (in `Polish_pl_appstore.tsv` ), it doesn't differ much from proposed by @senpl - I updated the file with this version.

> 1. Aplikacja Daily Dozen musi być zainstalowana na telefonie z systemem Android. Możesz ją pobrać tutaj: https://play.google.com/store/apps/details?id=org.nutritionfacts.dailydozen 
> 2. Stuknij w plik kopii zapasowej załączony w tym e-mailu. 
> 3. Wybierz opcję „Otwórz przy pomocy Daily Dozen”.


## 4. `debug`

As for `debug` - I am not sure about the context @marc-medley ? 
I think the proper way would be to say [debugowanie](https://pl.wikipedia.org/wiki/Debugowanie) in Polish. And I am not sure if we need to leave this clarification in the brackets. For now I left `debugowanie`.


## 5. Small changes

- from `będą zastąpione` to `zostaną zastąpione`:

  > Wszystkie istniejące dane zostaną zastąpione. Czy chcesz kontynuować?

- from `wytwórz` to `stwórz`. It sounds more natural:

  > Generate Weight Data - Stwórz pomiary wagi

- in translation of `No email apps found` - Nie znaleziono aplikacji poczty e-mail.
- In the sentence:

    > Do you like this app? - Czy lubisz tę aplikację?

I changed the word `naszą` (ours) to `tę` (this). I don't think it is needed to indicate possession in this case.
- I corrected the translation of `Evening` to **Wieczór** , as proposed `Południe` in English is 'Afternoon'.
- I modified slightly the sentence below. I changed **by** to **aby** and I omitted the word `(backup)` - I think there is no need to leave it there while we had the Polish word there already. I put `przywrócić` (to restore) in place of `odtworzyć`(to recreate).


  > Wykonaj następujące kroki, aby przywrócić swoją kopię zapasową w aplikacji Daily Dozen. 
_(Follow these steps to restore this backup in the Daily Dozen app.)_


## 6. `Feedback`

The previous translation of 'Please give us feedback in the Play Store.' :

> Proszę day nam informację zwrotną w sklepie Play.

doesn't sound very natural. I proposed this one:

> Zostaw nam opinię w sklepie Play.

Analogically, I changed the `Give Feedback` to `Zostaw opinię`.
 

## 7. A bit more changes

- I made a bit more changes when translating the sentence

  > Backing up your data requires you to have an email app installed so you can email the .csv backup file to yourself. Please install an email app and try again.

In my version, I decided to be a bit more specific - it might be more clear for some people what to do and how: 

  > Tworzenie kopii zapasowej twoich danych wymaga zainstalowania aplikacji do obsługi poczty e-mail, aby można było wysłać do siebie plik kopii zapasowej ".csv" . Zainstaluj aplikację e-mail i spróbuj ponownie.

-  I modified the translation of 

  > Can\'t backup without permission to write to storage.

And, as before, I changed the word **backup** to **kopia zapasowa**.


## 8. `moving average`

**moving average** relates to statistics.

> In statistics, a moving average (rolling average or running average) is a calculation to analyze data points by creating a series of averages of different subsets of the full data set. 

The Polish equivalent would be `średnia ruchoma`. I made a correction in the file.


## 9. `Streaks`

The last thing, I wanted to discuss is `streaks`. As I am not sure I agree fully on the proposed name `nawyki` (habits) here. 
**But I am also not against them.**
My thoughts on the subject:

According to the Cambridge Dictionary, **streak** means:

> something that happens or is done over a period of time without a break

It is hard to call something a habit (nawyk) if it happens for only 3 days, being followed by 7 days of it not happening. The point here is to make a habit out of something, and the more somebody is keeping the streak of doing/not doing something (like drinking 5 glasses of water every day or not eating sweets) the closest one is to create a good habit. 

I understand that the Polish equivalents **passa** (an unbroken series of events), **pasmo** (a certain amount of something gathered together; a series of successive events or phenomena) or even **kontinuum** (an unbroken series of events) don't exactly sound nice/proper in our case. 

I was thinking of using one of the words implying the coming-one-after-another feel, like serie (series), cykle (cycles), szeregi (arrays), ciągi (strings), sekwencje (sequences). 

The word `serie` fits quite ok, I think:


> Your database will now be upgraded to support the new streaks feature. - Twoja baza danych zostanie uaktualniona by wspierać nową funkcję serii.
> New feature: Streaks! - Nowa funkcja: Serie!
> Calculating streaks - Obliczanie serii


:bulb: Any other ideas and food for thought are welcome. 


And same as for `Tweaks`, it is also true for the `Streaks`:

> I'd leave the decision up to the person in charge of the app updates. And it definitely should be adjusted later, when the official Polish translation of 21 Tweaks comes out in another of Dr Greger's books, to agree with the app's terminology.

## 10. Typos

I also fixed some typos.

(kopi -> kopii, adres url -> adresu url, zainstaowania -> zainstalowania, 6 miesiące - 6 miesięcy, przywóceniem -> przywróceniem, histori -> historii)

**Comment by marc-medley** [comment]
@Hangur Some comments...

**1. `Tweak`** The English context use for _tweaks_ is to "improve by making fine adjustments". This definition agrees with the word `adaptacji` as you've described and proposed. So, `adaptacji` for now.

**4. `Debug`** The context for `debug` does refer to the computer programming process of finding and resolving "bugs" (defects or problems).

* [https://pl.wikipedia.org/wiki/Debugowanie](https://pl.wikipedia.org/wiki/Debugowanie)
* [https://en.wikipedia.org/wiki/Debugging](https://en.wikipedia.org/wiki/Debugging)

**9. `Streaks`** Yes, the correct `streak` context definition is _"something that happens or is done over a period of time without a break"._  Or, alternately stated, a Daily Dozen streak is a _continuous series (or sequence) of successful completions._ 

The Daily Dozen application `streak` reward feature shows an achievement color when an item has been _checked completed for multiple contiguous days._ The achievement colors are: bronze (2-6 days), silver (7-13 days), and gold (14 days or more). 

The `streak` achievement reward feature is part of the application. I did not find the app `streak` achievement reward mentioned in the _"How Not to Die"_ and _"How Not to Diet"_ books. 

The word `serie` appears to be a good choice based on your description and proposal. So, you may proceed with `serie`, unless the above explanation changes your mind.

**Comment by senpl** [comment]
I do not like `serie` as this got many meaning in polish (and usually not used in archive series, but product series). And is not as self describing as nawyki.

**Comment by marc-medley** [comment]
@Hangur and @senpl  Great feedback! thanks. 

> It is hard to call something a habit (nawyk) if it happens for only 3 days, being followed by 7 days of it not happening. The point here is to make a habit out of something, and the more somebody is keeping the streak of doing/not doing something (like drinking 5 glasses of water every day or not eating sweets) the closest one is to create a good habit.

I think the above comments from @Hangur on `habit` (`nawyk`) are valid; and, that `nawyk` should not be preferred is this context.

> `serie` as this got many meaning in polish (and usually not used in archive series, but product series). And is not as self describing

From @senpl comments, I understand that the word `serie` has many meanings and may not communicate clearly to the user.

So, let us revisit some underlaying details...

**1. Software Feature**

An _indicator_ which shows the number of _consecutive days completed_ is a Daily Dozen software feature.

![Days](https://user-images.githubusercontent.com/15098151/107712590-88b25600-6c7e-11eb-8649-2e385759d518.png)

This "consecutive days completed" software indicator is not discussed in Dr Greger's books and is not written about on the Nutrition Facts website. "Streaks" in the medical writings can have a different meaning, such as "fatty streaks in arteries".  Also, there is no branding effort around this features name.

_Therefore, the scope is to have a clear, understandable description of this software feature for a regional user._

**2. English Idiom**

The single English word `streak` has many meanings, and can be awkward to use, and may not describe this software feature to a user without context.

* [Wikinary: streak](https://en.wiktionary.org/wiki/streak)

The use of `streak` is similar to the English idiom ["winning streak"](https://idioms.thefreedictionary.com/winning+streak) which means _"a consecutive series of victories, successes, or instances of good fortune"_ or simply, _"consecutive wins"_

For the Daily Dozen apps, the software feature literally shows a _consecutive sequence count of recorded achievements_.

So, some "words implying the coming-one-after-another feel" is appropriate.

**3. App Phrases**

Consider the conceptual phrases below, as stated in English without using the word `streak`.

* "Your database will now be upgraded to support a new Consecutive Days Completed indicator."
* "New feature: Consecutive Days Completed!"
* "Calculating consecutive days completed"

_Note: Using more than one word for `streak` is OK, if needed. The software screen layout can adjust to the text length. Fewer words is preferred only if the user can still understand the resulting text._

@Hangur How would you communicate the above in Polish phrases? Would adding some modifier word(s) to `serie` possibly fix the mentioned issues with `serie`? Or, would you propose something different based on the above details?  Perhaps a translation of "consecutive days completed" would communicate accurately to a Polish speaking user?

@senpl Your thoughts on the same above? What word(s) would you propose instead of `habit` (`nawyk`)?

**Comment by Hangur** [comment]
@senpl I am not sure which other meanings of the Polish word `serie` might interfere with the understanding of the word I proposed? 

According to the [Polish dictionary](https://sjp.pwn.pl/sjp/seria;2520051.html#:~:text=%C2%ABzestawienie%2012%20d%C5%BAwi%C4%99k%C3%B3w%20o%20r%C3%B3%C5%BCnej,%2C%20barwie%2C%20artykulacji%20itp.%C2%BB), the meaning for **seria** is primarily:

> 1. "a series of consecutive activities or events"

And then, indeed, it has other meanings, but it all depends on the context you put the word in. (It is the same as @marc-medley  mentioned about the **streaks**.)

> 2. "a collection of objects that are the same or constitute a whole"
> 3. "a series of shots or bursts in rapid succession"
> 4. "a certain number of industrial products made according to the same documentation"
> 5. "group of successive rock layers with common features"
> 6. "stratigraphic unit of the division of geological formations"
> 7. «a combination of 12 sounds of different pitch and duration, volume, timbre, articulation, etc.»

Did you maybe have some other thing(s) on your mind? :thinking:  Maybe we can tweak **serie** in some way, or maybe you can think of something different than **nawyk** or **serie** altogether? Or maybe you also agree that the `Consecutive Days Completed` would communicate more accurately to a Polish speaking user, and we can then drop the **serie** and **nawyk**.

@marc-medley , I guess I would like first to determine where would the word `streaks` appear in the app? I think the context might influence greatly the translation of the word. Is it going to be shown in the way the English version of the app is showing `14 days` , it being displayed under the beans (berries, other fruits etc.)? If that's the case then I think it would be correct to say `z rzędu` (I attached the pic below to visualize how I see it), which corresponds to the English `in a row`, and would be really fitting to show in the Polish app how many consecutive days of eating beans/berries/etc. have passed. It would be much better than `serie`. It could be **14 dni w serii** but it lacks clarity.

![daily dozen 01](https://user-images.githubusercontent.com/44006666/107761541-d33ddc00-6d2b-11eb-8bf9-f43331ec25fe.jpg)
![daily dozen 02](https://user-images.githubusercontent.com/44006666/107761544-d3d67280-6d2b-11eb-8469-8295a1853e95.jpg)


Or would it also be appearing somewhere in the same way - with an introduction, like for example Tweak 'preload with water' has its own introduction?

This is what I meant:

![daily dozen 03](https://user-images.githubusercontent.com/44006666/107758656-7dffcb80-6d27-11eb-83be-095218c8d5dc.jpg)
![daily dozen 04](https://user-images.githubusercontent.com/44006666/107758661-7e986200-6d27-11eb-81e3-d7fd7f6bf2f7.jpg)


@marc-medley , for the question about `serie` 

> Would adding some modifier word(s) to `serie` possibly fix the mentioned issues with `serie`?

that you asked, it depends on the answer to my questions above. I think I need a bit more context, to put everything in a proper perspective. But a translation of `consecutive days completed`, you proposed, seems like a much better choice than **serie**.

> Or, would you propose something different based on the above details? Perhaps a translation of "consecutive days completed" would communicate accurately to a Polish speaking user?

A translation of **consecutive days completed** might communicate more accurately to a Polish speaking user. It is more clear what it is about and it implies that it is about completing something in a row of days, without an interruption. I would prefer to use this way than the `serie` I proposed earlier.

**My proposal for the English sentences**

> Your database will now be upgraded to support a new Consecutive Days Completed indicator.
New feature: Consecutive Days Completed!
Calculating consecutive days completed

**is the following:**

> Twoja baza danych zostanie uaktualniona by wspierać nowy wskaźnik "Ukończonych dni z rzędu".
> Nowa funkcja: "Ukończone dni z rzędu"!
> Obliczanie "Ukończonych dni z rzędu".

**Comment by Hangur** [comment]
@marc-medley , I think I haven't conveyed my thoughts properly. I asked for the context for `debug` in order to determine whether it requires any changes in the form of the Polish translation (**debugowanie**). I wasn't sure if **debug** should be translated into a command (in Polish **debuguj**, a verb) or leaving it as a description (**debugowanie**, a gerund / noun).

**Comment by marc-medley** [comment]
@Hangur Some answers to your questions below:

**Debug**

The word "Debug" is used as a description heading like a section title.

**Streaks / Consecutive Days Completed**

Currently, the `14 days` in English will show as `14 dni` in Polish. This is screen area is small so the fewest words possible is best.

The word "streak" is not shown to the iPhone user. The indicator "N days", in English, is generally understood as the user looks at different dates. 

The "Streaks / Consecutive Days Completed" feature does not have any "About Streaks" screen information view to give the feature a name and describe the feature details.  So, this situation prefers some unambigous, self-explanatory word(s).  

Android has a progress indicator which says "Calculating streaks" when calculation of the consecutive days completed may appear slow to the user. This "Calculating ..." indicator is transient and may not be noticed by the user.

Android uses "Your database will now be upgraded to support the new streaks feature." and "New feature: Streaks!" is for a _user that upgrades from a version older than the 2016 version 8_. New users do not see these two messages because the feature is already supported by the newer releases.

**Comment by senpl** [comment]
> @senpl Your thoughts on the same above? What word(s) would you propose instead of `habit` (`nawyk`)?
My voice go to `progres`, or `postęp`.

**Comment by marc-medley** [comment]
@Hangur, I'm ok with how `progress` reads in English as @senpl proposed. Here is the use of `progress` in the English phrases:

• "Your database will now be upgraded to support a new progress feature."
• "New progress feature!"
• "Calculating progress"

The word `progress` is simple and general. Simplified wording is consistent with the application description at [https://nutritionfacts.org/daily-dozen](https://nutritionfacts.org/daily-dozen/).

@Hangur If you also find the Polish word(s) for English `progress` to be reasonably acceptable, then let's use translations of `progress` based on the above English phrases.  You would need to select `progres`, `postęp` or some other corresponding Polish translation. (I don't currently have an understanding of how the Polish words `progres` or `postęp` might be different.)

Thanks.

--marc @marc-medley

**Comment by Hangur** [comment]
@marc-medley I am ok with both `progres` and `postęp`. They are good proposals :+1: 

The words are synonyms and there is no significant difference between them. I like the latter (`postęp`) more, it is a natural Polish word (while **progres** was derived from French). But that is a matter of personal preferences - whichever one is chosen, it is perfectly fine.

>Twoja baza danych zostanie uaktualniona by wspierać nową funkcję postępu / progresu.
Nowa funkcja: Postęp / Progres!
Obliczanie postępu / progresu.

**Comment by marc-medley** [comment]
@Hangur I will proceed with `postęp`.

* Twoja baza danych zostanie uaktualniona by wspierać nową funkcję postępu.
* Nowa funkcja: Postęp!  (... see note below) 
* Obliczanie postępu.

**Note: "new feature"**

Consider the following two English phrases:

(A) New progress feature!
(B) New feature: Progress!

(A) "New progress feature!" alerts the user that some new progress feature has been added. However, the feature is unnamed. This is ok because the feature will become self-apparent as the app is used. A name is not required for the feature to be understood and appreciated.

(B) "New feature: Progress!" indicates a feature name of `Progress`. However, the name is not used directly in the app. In other words, the added feature does not show a formal name. Also, the app has several other achievement indicators. Thus, any choosen name may end up unassociated with the feature and forgotten in the user's mind.

Based on the above thoughts, I would propose a Polish version similar to "New progress feature!" or "New progress feature added!" without a formal feature name. Your thoughts?

**zloty/dollar/none options**

Any comment (or preference) on the zloty/dollar/none options?

* Use `dollar` and `cent`.
* Use `zloty` in a way that approximates the regional cost ratio
* Use simplified terms without either `dollar` or `zloty`

**Comment by Hangur** [comment]
@marc-medley

> Based on the above thoughts, I would propose a Polish version similar to "New progress feature!" or "New progress feature added!" without a formal feature name. Your thoughts?

Then I would go for : 
- `Nowa funkcja postępu!` (**New progress feature!**) 
- `Dodano nową funkcję postępu!` (**"New progress feature added!"**) - I am leaning more towards this one.

As for 

> Any comment (or preference) on the zloty/dollar/none options?
> - Use `dollar` and `cent`.
> - Use `zloty` in a way that approximates the regional cost ratio
> - Use simplified terms without either `dollar` or `zloty`

Originally, I translated it using **dollar** and **cent**, but because I am not sure how many Polish people are aware of the value of American currency (also, it isn't very natural to use the other country's currency when talking about "local" products), I would skip it and go for one of the two other options. 
And I am hesitating here, because for me they are equivalent and I am okay with both - slightly leaning to not being so specific about the number: aka your **simplified terms**.

If you let me know which one you prefer, I will make sure to adjust the translation.

**Comment by marc-medley** [comment]
@Hangur Let's go with the simplified terms which is not specific about numbers. Thanks.

**Comment by Hangur** [comment]
In some places I removed the **, i** (**, and**) altogether - looking at it now, I don't think it is necessary, just a comma instead is enough.

I also noticed that I have somehow missed the line with `Lentils (beluga, french, and red varieties)`, so I added the corresponding translations (`Soczewica (beluga, francuska du Puy i czerwone odmiany)`). 


## zloty/dollar/none options 

I updated the translation based on the discussion above.


> (...) but a pinch a day would cost a dollar, whereas a teaspoon of cumin costs less than ten cents.
`(...) ale zaledwie szczypta dziennie kosztowałaby więcej niż jedna łyżeczka kminku.`
(just a pinch a day would cost more than one teaspoon of cumin.)

> (...) can reduce body fat at a cost of perhaps two cents a day.
`(...) może zmniejszyć tkankę tłuszczową - za jedynie grosze.`
(can reduce body fat - for just pennies.)

The expression **za (zaledwie) grosze** means colloquially **cheaply**, it's the English equivalent of **for (just) pennies**.


## updated file(s): 
[Polish_pl.tsv.txt](https://github.com/nutritionfactsorg/daily-dozen-localization/files/6013001/Polish_pl.tsv.txt)

I wasn't sure if I should also update the `Polish_pl_Additions.tsv` with the `postęp` that we were talking about above - just in case I did that as well. I changed what was before in `base_value` (**streaks** to **progress**) and then added the proper translation in `lang_value` (**postęp**). Ignore, if that was not needed.

[Polish_pl_Additions.tsv.txt](https://github.com/nutritionfactsorg/daily-dozen-localization/files/6013116/Polish_pl_Additions.tsv.txt)


:sound:  If there are any other issues, please let me know.

**Comment by marc-medley** [comment]
@Hangur The iPhone app with Polish language support is now in [TestFlight](https://developer.apple.com/testflight/) testing for release.

One item was found that needs translation. Please see `dozeOtherInfo.message` near the end of the current [Polish/tsv/Polish_pl_additions.tsv](https://github.com/nutritionfactsorg/daily-dozen-localization/blob/master/Languages/Polish/tsv/Polish_pl_additions.tsv).  I had previously missed adding this text to the spreadsheets.

Here are some screen shots from the test release version 3.2.7 build 3. Please let me know if anything does not look correct to you. [DailyDozen iPhone v3.2.7(3) jpeg.zip](https://github.com/nutritionfactsorg/daily-dozen-localization/files/6065499/DailyDozen.iPhone.v3.2.7.3.jpeg.zip)

**Comment by Hangur** [comment]
@marc-medley , I added the missing thing.

I also corrected one thing (`Servings History`) that was translated to Spanish (`Historial de porciones`), I believe :) It is now having the Polish translation (`Historia porcji`).

All changes are reflected in the file below.
[Polish_pl_additions.tsv.txt](https://github.com/nutritionfactsorg/daily-dozen-localization/files/6068396/Polish_pl_additions.tsv.txt)

I went through the screen shots - they look good! :+1:

**Comment by Hangur** [comment]
@marc-medley, I was checking the Daily Dozen App updates and I noticed that I am not mentioned as a contributor at all, is it something you can take a look into/remedy?

![Screenshot_2021-03-08-17-09-35-74](https://user-images.githubusercontent.com/44006666/110347984-7505cf80-8031-11eb-8500-a49cf7c866f8.jpg)

**Comment by slavick** [comment]
@Hangur I've updated the release notes in Google Play. It should be live in a bit. Sorry for leaving you out, I was just looking at the PRs in the android repo.

**Comment by Hangur** [comment]
@slavick thanks a lot! Already can see it!

@slavick @marc-medley on another note, I noticed a small inconsistency (an extra dot where it shouldn't be any) - just in case I will look at the whole thing again, for any other such. My question is, what's the preferred way to submit changes? 

- With a PR to this repository and a new issue?
- With a PR to this repository on this issue? 
- With submitting the edited `.tsv` file to this issue?
- Or with PRs to the IOS and Android apps respectively (editing the xml files).

**Comment by marc-medley** [comment]
@Hangur (and @slavick) It would be preferred to use the latest `.tsv` and re-summit to this issue. This will keep localization files in sync.

As FYI, the iOS language localization has 27(+) files per language where Android has only 1. Compare the difference in the number of source files to be managed for Polish in the following two directories:

* [Polish/android/values-pl](https://github.com/nutritionfactsorg/daily-dozen-localization/tree/master/Languages/Polish/android/values-pl)
* [Polish/ios/pl.xcloc](https://github.com/nutritionfactsorg/daily-dozen-localization/tree/master/Languages/Polish/ios/pl.xcloc)

**Comment by Hangur** [comment]
@marc-medley understood :+1: 

One question is where to get the latest `.tsv`s, because in the `master` [branch](https://github.com/nutritionfactsorg/daily-dozen-localization/tree/master/Languages/Polish/tsv) of this repo there are the empty templates and a partially updated `Polish_pl.tsv`.

**Comment by marc-medley** [comment]
@Hangur I will post the updated `.tsv` files. Could you also check the various screens on the Android device? In other words, do you see anything is addition to the "extra dot" which should be resolved in a minor code update?

@senpl [Android version 17.3 which includes the Polish translation is now available online.](https://play.google.com/store/apps/details?id=org.nutritionfacts.dailydozen&hl=en)  Please let us know if you find any issues while running the application on the device. Thanks.

**Comment by Hangur** [comment]
@marc-medley I saw that `Codzienny Tuzin` (`Daily Dozen`) in one or two places might in the wrong grammatical case, but I will check everything more thoroughly, just to be sure.

**Comment by marc-medley** [comment]
@Hangur Yes, a thorough check would be really helpful. At this time, you and @senpl are our Polish speaking testers. Also be aware if `\` formatting is properly in place. For example, a `\n` in the raw string should show as a new line. Thanks.

**Comment by marc-medley** [comment]
@Hangur Please use [Polish_pl.20210308.tsv](https://github.com/nutritionfactsorg/daily-dozen-localization/blob/master/Languages/Polish/tsv/Polish_pl.20210308.tsv) and [Polish_pl_appstore.20210308.tsv](https://github.com/nutritionfactsorg/daily-dozen-localization/blob/master/Languages/Polish/tsv/Polish_pl_appstore.20210308.tsv).

The previous version have been moved to the [history directory](https://github.com/nutritionfactsorg/daily-dozen-localization/tree/master/Languages/Polish/tsv/history).

The `20210308` versions were doubled checked based on the most recent info and builds that I see.  Note that the previous `additions` file is now include in the main tsv file.

Some observations: 

1. **Random IDs** The Random ID (like `XYD-fX-adn.*`) is a legacy approach to localization on the iOS platform. These Random IDs are [still being actively phased out on the Daily Dozen iOS app](https://github.com/nutritionfactsorg/daily-dozen-ios/issues/51).
2. **Polish Translation** My current checks find Polish translations to be in both the 20210308 and the history files. Please let me know if you see anything which needs to be included/updated in the 20210308 files.
3. **Android & Apple Keys** Some key cells will be blank because there is not a 1-to-1 mapping of phrases in many cases between the two platforms.
4. **Spreadsheet TSV Approach** Polish is the first language through the tsv spreadsheet approach for Android and Apple Daily Dozen apps.  It's an evolving process. Thank you for helping to make the process better for the translations to follow.

**Comment by Hangur** [comment]
@marc-medley , @senpl I made a few changes in the above-mentioned latest files, that I think should be included in the 20210308 files.


### A few changes

1. `Cherries (sweet or tart)` - in the Polish language we have two separate names for sweet cherries (`czereśnie`) and tart/sour cherries (`wiśnie`), so it actually makes much more sense than current translation. Somehow, I didn't fix it before.

2. I changed the grammatical cases of `Codzienny Tuzin` (**Daily Dozen**) where it was necessary.

3. I looked at the `21 Tweaks` again - the **descriptions** part, and I 'tweaked' them a bit more. While viewing them on my phone, I thought that some of the sentences sounded a bit wooden.

4. I also changed the thing below. Because `Weight (lbs)` is `Waga (funt)`, not `Waga (kg)`. Lbs is an imperial unit and somehow **kg** got mixed in here.

![weight](https://user-images.githubusercontent.com/44006666/110544696-77991f80-812c-11eb-9fc4-e2218d5fa46f.png)

5. Apart from that, I removed some extra dots & commas, added a missing letter.


### Small concerns

1. Some of the things don't seem like they were translated into Polish, even though they were on the `.tsv` file. Is this is how it supposed to be? Also the red link („How not to diet”) in the pic below doesn't include the letter 't' for some reason:

![Screenshot_2021-03-09-20-08-50](https://user-images.githubusercontent.com/44006666/110543854-20467f80-812b-11eb-9556-fc9afe036d68.png)


2. This concern is more of a consistency/aesthetics nature. When I look at the app on my phone - it doesn't leave the spaces after numbers (see: **1szklanka pokrojonych owoców** & **3szklanki popcornu** vs the other things listed there). Even though in the `.tsv` file it was/is written correctly, with a space. 

![Screenshot_2021-03-09-20-59-16](https://user-images.githubusercontent.com/44006666/110544170-9a770400-812b-11eb-89fb-b8bf1437e116.png)

![Screenshot_2021-03-09-21-02-22](https://user-images.githubusercontent.com/44006666/110544174-9ba83100-812b-11eb-80d2-4027118be1c7.png)


## Updated files:

[Polish_pl_appstore.20210309.tsv.txt](https://github.com/nutritionfactsorg/daily-dozen-localization/files/6111744/Polish_pl_appstore.20210309.tsv.txt)
[Polish_pl.20210309.tsv.txt](https://github.com/nutritionfactsorg/daily-dozen-localization/files/6111745/Polish_pl.20210309.tsv.txt)

**Comment by marc-medley** [comment]
Thank you for your contributions.
